#!/usr/bin/env python3
"""Turns a WAV into a C header holding a mono 16-bit 48 kHz clip for the bench build.

Stereo is folded to mono by taking the left channel. The clip loops in place of the SAI
input while the bench command 'v' is on.

  ./make_clip.py ../samples/adam_vox_sample2_4s.wav /tmp/cubevox-fw/gen/bench_clip.h
"""

import sys
import wave

import numpy as np


def main():
    src, dst = sys.argv[1], sys.argv[2]
    w = wave.open(src)
    ch, sw, sr, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
    raw = w.readframes(n)
    w.close()
    if sr != 48000 or sw != 2:
        sys.exit(f"[ERROR] {src}: need 48 kHz 16-bit, got {sr} Hz {sw * 8}-bit")
    x = np.frombuffer(raw, np.int16).reshape(-1, ch)[:, 0]
    with open(dst, "w") as f:
        f.write(f"// Generated by make_clip.py from {src}: {len(x)} samples, 48 kHz mono int16.\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"constexpr uint32_t kBenchClipLen = {len(x)};\n")
        f.write("const int16_t kBenchClip[kBenchClipLen] = {\n")
        for i in range(0, len(x), 16):
            f.write("  " + ",".join(str(v) for v in x[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"[clip] {src}: {len(x) / sr:.2f} s mono, {len(x) * 2 // 1024} KB of flash")


if __name__ == "__main__":
    main()
